name: project_app
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: 4.17.5
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  google_fonts: ^6.1.0
  share_plus: ^7.1.0
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/event_background.jpg
    - assets/animations/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins.ttf
